//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSimulator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HTBTrackerEntities : DbContext
    {
        public HTBTrackerEntities()
            : base("name=HTBTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spVerifyGeofencePoint_Result> spVerifyGeofencePoint(string lat, string lng)
        {
            var latParameter = lat != null ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(string));
    
            var lngParameter = lng != null ?
                new ObjectParameter("Lng", lng) :
                new ObjectParameter("Lng", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spVerifyGeofencePoint_Result>("spVerifyGeofencePoint", latParameter, lngParameter);
        }
    }
}
